language: node_js

node_js: lts/*

cache:
  yarn: true

before_install:
  - openssl aes-256-cbc -K $encrypted_3fd66475d68b_key -iv $encrypted_3fd66475d68b_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

install:
  - yarn

before_script:
  - yarn lint

script:
  - yarn test --coverage
  - yarn build

after_script:
  - yarn coveralls
  - chmod 600 ~/.ssh/id_rsa
  - scp -r -o StrictHostKeyChecking=no -P $REMOTE_PORT ./dist $REMOTE_HOST:$REMOTE_PATH
