language: node_js

node_js: lts/*

cache:
  yarn: true

install:
  - yarn

script:
  - yarn lint
  - yarn test --coverage

after_script:
  - yarn coveralls

before_install:
  - openssl aes-256-cbc -K $encrypted_3fd66475d68b_key -iv $encrypted_3fd66475d68b_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d

